In [4]:
import pandas as pd

df = pd.read_csv('/content/20200220_Rendimiento_2019_20200131_PUBL.csv', sep=';')
display(df.info())

/tmp/ipython-input-3623563451.py:3: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/20200220_Rendimiento_2019_20200131_PUBL.csv', sep=';')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3328915 entries, 0 to 3328914
Data columns (total 37 columns):
 #   Column          Dtype
---  ------          -----
 0   AGNO            int64
 1   RBD             int64
 2   DGV_RBD         int64
 3   NOM_RBD         object
 4   COD_REG_RBD     int64
 5   NOM_REG_RBD_A   object
 6   COD_PRO_RBD     int64
 7   COD_COM_RBD     int64
 8   NOM_COM_RBD     object
 9   COD_DEPROV_RBD  int64
 10  NOM_DEPROV_RBD  object
 11  COD_DEPE        int64
 12  COD_DEPE2       int64
 13  RURAL_RBD       int64
 14  ESTADO_ESTAB    int64
 15  COD_ENSE        int64
 16  COD_ENSE2       int64
 17  COD_GRADO       int64
 18  LET_CUR         object
 19  COD_JOR         int64
 20  COD_TIP_CUR     int64
 21  COD_DES_CUR     int64
 22  MRUN            int64
 23  GEN_ALU         int64
 24  FEC_NAC_ALU     int64
 25  EDAD_ALU        object
 26  COD_REG_ALU     int64
 27  COD_COM_ALU     int64
 28  NOM_COM_ALU     object
 29  COD_RAMA        int64
 30  COD_SEC         int64
 31  COD_ESPE        int64
 32  PROM_GRAL       object
 33  ASISTENCIA      int64
 34  SIT_FIN         object
 35  SIT_FIN_R       object
 36  COD_MEN         int64
dtypes: int64(27), object(10)
memory usage: 939.7+ MB

None

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3375512 entries, 0 to 3375511
Data columns (total 55 columns):
 #   Column                 Dtype
---  ------                 -----
 0   agno                   int64
 1   rbd                    int64
 2   cod_reg_rbd            int64
 3   nom_reg_rbd_a          object
 4   cod_pro_rbd            int64
 5   cod_com_rbd            int64
 6   nom_com_rbd            object
 7   cod_deprov_rbd         int64
 8   nom_deprov_rbd         object
 9   rural_rbd              int64
 10  slep                   float64
 11  nombre_slep            object
 12  cohorte                float64
 13  cod_depe2              int64
 14  cod_ense               int64
 15  cod_ense2              int64
 16  cod_grado              int64
 17  let_cur                object
 18  mrun                   int64
 19  gen_alu                int64
 20  fec_nac_alu            int64
 21  dias_asistidos_3       float64
 22  dias_asistidos_4       float64
 23  dias_asistidos_5       float64
 24  dias_asistidos_6       float64
 25  dias_asistidos_7       float64
 26  dias_asistidos_8       float64
 27  dias_asistidos_9       float64
 28  dias_asistidos_10      float64
 29  dias_asistidos_11      float64
 30  dias_asistidos_12      float64
 31  dias_asistidos_anual   int64
 32  dias_trabajados_3      float64
 33  dias_trabajados_4      float64
 34  dias_trabajados_5      float64
 35  dias_trabajados_6      float64
 36  dias_trabajados_7      float64
 37  dias_trabajados_8      float64
 38  dias_trabajados_9      float64
 39  dias_trabajados_10     float64
 40  dias_trabajados_11     float64
 41  dias_trabajados_12     float64
 42  dias_trabajados_anual  int64
 43  tasa_asistencia_3      object
 44  tasa_asistencia_4      object
 45  tasa_asistencia_5      object
 46  tasa_asistencia_6      object
 47  tasa_asistencia_7      object
 48  tasa_asistencia_8      object
 49  tasa_asistencia_9      object
 50  tasa_asistencia_10     object
 51  tasa_asistencia_11     object
 52  tasa_asistencia_12     object
 53  tasa_asistencia_anual  object
 54  categoria_asis_anual   int64
dtypes: float64(22), int64(17), object(16)
memory usage: 1.4+ GB

None

In [5]:
import pandas as pd

df_rendimiento = pd.read_csv('/content/20200220_Rendimiento_2019_20200131_PUBL.csv', sep=';')
df_asistencia = pd.read_csv('/content/Asistencia_anual_2019.csv', sep=';')

print("df_rendimiento info:")
display(df_rendimiento.info())
print("\ndf_asistencia info:")
display(df_asistencia.info())

/tmp/ipython-input-3029675229.py:3: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df_rendimiento = pd.read_csv('/content/20200220_Rendimiento_2019_20200131_PUBL.csv', sep=';')
/tmp/ipython-input-3029675229.py:4: DtypeWarning: Columns (11,43,44,45,46,47,48,49,50,51,52,53) have mixed types. Specify dtype option on import or set low_memory=False.
  df_asistencia = pd.read_csv('/content/Asistencia_anual_2019.csv', sep=';')

df_rendimiento info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3328915 entries, 0 to 3328914
Data columns (total 37 columns):
 #   Column          Dtype
---  ------          -----
 0   AGNO            int64
 1   RBD             int64
 2   DGV_RBD         int64
 3   NOM_RBD         object
 4   COD_REG_RBD     int64
 5   NOM_REG_RBD_A   object
 6   COD_PRO_RBD     int64
 7   COD_COM_RBD     int64
 8   NOM_COM_RBD     object
 9   COD_DEPROV_RBD  int64
 10  NOM_DEPROV_RBD  object
 11  COD_DEPE        int64
 12  COD_DEPE2       int64
 13  RURAL_RBD       int64
 14  ESTADO_ESTAB    int64
 15  COD_ENSE        int64
 16  COD_ENSE2       int64
 17  COD_GRADO       int64
 18  LET_CUR         object
 19  COD_JOR         int64
 20  COD_TIP_CUR     int64
 21  COD_DES_CUR     int64
 22  MRUN            int64
 23  GEN_ALU         int64
 24  FEC_NAC_ALU     int64
 25  EDAD_ALU        object
 26  COD_REG_ALU     int64
 27  COD_COM_ALU     int64
 28  NOM_COM_ALU     object
 29  COD_RAMA        int64
 30  COD_SEC         int64
 31  COD_ESPE        int64
 32  PROM_GRAL       object
 33  ASISTENCIA      int64
 34  SIT_FIN         object
 35  SIT_FIN_R       object
 36  COD_MEN         int64
dtypes: int64(27), object(10)
memory usage: 939.7+ MB

None

df_asistencia info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3375512 entries, 0 to 3375511
Data columns (total 55 columns):
 #   Column                 Dtype
---  ------                 -----
 0   agno                   int64
 1   rbd                    int64
 2   cod_reg_rbd            int64
 3   nom_reg_rbd_a          object
 4   cod_pro_rbd            int64
 5   cod_com_rbd            int64
 6   nom_com_rbd            object
 7   cod_deprov_rbd         int64
 8   nom_deprov_rbd         object
 9   rural_rbd              int64
 10  slep                   float64
 11  nombre_slep            object
 12  cohorte                float64
 13  cod_depe2              int64
 14  cod_ense               int64
 15  cod_ense2              int64
 16  cod_grado              int64
 17  let_cur                object
 18  mrun                   int64
 19  gen_alu                int64
 20  fec_nac_alu            int64
 21  dias_asistidos_3       float64
 22  dias_asistidos_4       float64
 23  dias_asistidos_5       float64
 24  dias_asistidos_6       float64
 25  dias_asistidos_7       float64
 26  dias_asistidos_8       float64
 27  dias_asistidos_9       float64
 28  dias_asistidos_10      float64
 29  dias_asistidos_11      float64
 30  dias_asistidos_12      float64
 31  dias_asistidos_anual   int64
 32  dias_trabajados_3      float64
 33  dias_trabajados_4      float64
 34  dias_trabajados_5      float64
 35  dias_trabajados_6      float64
 36  dias_trabajados_7      float64
 37  dias_trabajados_8      float64
 38  dias_trabajados_9      float64
 39  dias_trabajados_10     float64
 40  dias_trabajados_11     float64
 41  dias_trabajados_12     float64
 42  dias_trabajados_anual  int64
 43  tasa_asistencia_3      object
 44  tasa_asistencia_4      object
 45  tasa_asistencia_5      object
 46  tasa_asistencia_6      object
 47  tasa_asistencia_7      object
 48  tasa_asistencia_8      object
 49  tasa_asistencia_9      object
 50  tasa_asistencia_10     object
 51  tasa_asistencia_11     object
 52  tasa_asistencia_12     object
 53  tasa_asistencia_anual  object
 54  categoria_asis_anual   int64
dtypes: float64(22), int64(17), object(16)
memory usage: 1.4+ GB

None

Now that we have both DataFrames loaded, we can look for common columns to merge them.

From a quick look at their `info()`, here are some potential common columns, considering slight naming differences (e.g., `AGNO` vs `agno`, `RBD` vs `rbd`, `MRUN` vs `mrun`):

*   **Student Identifier**: `MRUN` in `df_rendimiento` and `mrun` in `df_asistencia`
*   **Year**: `AGNO` in `df_rendimiento` and `agno` in `df_asistencia`
*   **School Identifier**: `RBD` in `df_rendimiento` and `rbd` in `df_asistencia`
*   **Grade/Course**: `COD_GRADO` and `LET_CUR` in `df_rendimiento`, and `cod_grado` and `let_cur` in `df_asistencia`

To perform a merge, we usually align records based on one or more common identifier columns. For student-level data across different records, the student's unique ID (`MRUN`/`mrun`) and the year (`AGNO`/`agno`) are often good candidates for a primary key.

Could you please confirm which columns you'd like to use to merge these two DataFrames and what type of merge you intend to perform (e.g., an 'inner' merge to keep only matching records, a 'left' merge to keep all records from `df_rendimiento` and add matching attendance data, etc.)?

In [3]:
print("Unique values in 'nom_reg_rbd_a' from df_merged:")
display(df_merged['nom_reg_rbd_a'].unique())

Unique values in 'nom_reg_rbd_a' from df_merged:

NameError: name 'df_merged' is not defined

In [6]:
print("Unique values in 'nom_reg_rbd_a' from df_asistencia:")
display(df_asistencia['nom_reg_rbd_a'].unique())

Unique values in 'nom_reg_rbd_a' from df_asistencia:

array(['RM', 'TPCA', 'BBIO', 'COQ', 'VALPO', 'AYSEN', 'MAULE', 'NUBLE',
       'ANTOF', 'ARAUC', 'RIOS', 'AYP', 'LGBO', 'ATCMA', 'LAGOS', 'MAG'],
      dtype=object)

In [8]:
print("Info of df_merged_rm:")
display(df_merged_rm.info())

print("\nFirst 5 rows of df_merged_rm:")
display(df_merged_rm.head())

Info of df_merged_rm:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1041742 entries, 0 to 1041741
Data columns (total 88 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   agno                   1041742 non-null  int64
 1   rbd                    1041742 non-null  int64
 2   DGV_RBD                1041742 non-null  int64
 3   NOM_RBD                1041742 non-null  object
 4   COD_REG_RBD            1041742 non-null  int64
 5   nom_reg_rbd_a          1041742 non-null  object
 6   COD_PRO_RBD            1041742 non-null  int64
 7   COD_COM_RBD            1041742 non-null  int64
 8   NOM_COM_RBD            1041742 non-null  object
 9   COD_DEPROV_RBD         1041742 non-null  int64
 10  NOM_DEPROV_RBD         1041742 non-null  object
 11  COD_DEPE               1041742 non-null  int64
 12  COD_DEPE2              1041742 non-null  int64
 13  RURAL_RBD              1041742 non-null  int64
 14  ESTADO_ESTAB           1041742 non-null  int64
 15  COD_ENSE               1041742 non-null  int64
 16  COD_ENSE2              1041742 non-null  int64
 17  COD_GRADO              1041742 non-null  int64
 18  LET_CUR                1041742 non-null  object
 19  COD_JOR                1041742 non-null  int64
 20  COD_TIP_CUR            1041742 non-null  int64
 21  COD_DES_CUR            1041742 non-null  int64
 22  mrun                   1041742 non-null  int64
 23  GEN_ALU                1041742 non-null  int64
 24  FEC_NAC_ALU            1041742 non-null  int64
 25  EDAD_ALU               1041742 non-null  object
 26  COD_REG_ALU            1041742 non-null  int64
 27  COD_COM_ALU            1041742 non-null  int64
 28  NOM_COM_ALU            1041742 non-null  object
 29  COD_RAMA               1041742 non-null  int64
 30  COD_SEC                1041742 non-null  int64
 31  COD_ESPE               1041742 non-null  int64
 32  PROM_GRAL              1041742 non-null  object
 33  ASISTENCIA             1041742 non-null  int64
 34  SIT_FIN                1041742 non-null  object
 35  SIT_FIN_R              1041742 non-null  object
 36  COD_MEN                1041742 non-null  int64
 37  cod_reg_rbd            1041742 non-null  int64
 38  cod_pro_rbd            1041742 non-null  int64
 39  cod_com_rbd            1041742 non-null  int64
 40  nom_com_rbd            1041742 non-null  object
 41  cod_deprov_rbd         1041742 non-null  int64
 42  nom_deprov_rbd         1041742 non-null  object
 43  rural_rbd              1041742 non-null  int64
 44  slep                   20796 non-null    float64
 45  nombre_slep            20796 non-null    object
 46  cohorte                20796 non-null    float64
 47  cod_depe2              1041742 non-null  int64
 48  cod_ense               1041742 non-null  int64
 49  cod_ense2              1041742 non-null  int64
 50  cod_grado              1041742 non-null  int64
 51  let_cur                1041742 non-null  object
 52  gen_alu                1041742 non-null  int64
 53  fec_nac_alu            1041742 non-null  int64
 54  dias_asistidos_3       1013467 non-null  float64
 55  dias_asistidos_4       1022216 non-null  float64
 56  dias_asistidos_5       1027227 non-null  float64
 57  dias_asistidos_6       942442 non-null   float64
 58  dias_asistidos_7       1033018 non-null  float64
 59  dias_asistidos_8       1036880 non-null  float64
 60  dias_asistidos_9       1038585 non-null  float64
 61  dias_asistidos_10      1038681 non-null  float64
 62  dias_asistidos_11      1006839 non-null  float64
 63  dias_asistidos_12      956359 non-null   float64
 64  dias_asistidos_anual   1041742 non-null  int64
 65  dias_trabajados_3      1013467 non-null  float64
 66  dias_trabajados_4      1022216 non-null  float64
 67  dias_trabajados_5      1027227 non-null  float64
 68  dias_trabajados_6      942442 non-null   float64
 69  dias_trabajados_7      1033018 non-null  float64
 70  dias_trabajados_8      1036880 non-null  float64
 71  dias_trabajados_9      1038585 non-null  float64
 72  dias_trabajados_10     1038681 non-null  float64
 73  dias_trabajados_11     1006839 non-null  float64
 74  dias_trabajados_12     956359 non-null   float64
 75  dias_trabajados_anual  1041742 non-null  int64
 76  tasa_asistencia_3      1013467 non-null  object
 77  tasa_asistencia_4      1022216 non-null  object
 78  tasa_asistencia_5      1027227 non-null  object
 79  tasa_asistencia_6      942442 non-null   object
 80  tasa_asistencia_7      1033018 non-null  object
 81  tasa_asistencia_8      1036880 non-null  object
 82  tasa_asistencia_9      1038585 non-null  object
 83  tasa_asistencia_10     1038681 non-null  object
 84  tasa_asistencia_11     1006839 non-null  object
 85  tasa_asistencia_12     956359 non-null   object
 86  tasa_asistencia_anual  1041742 non-null  object
 87  categoria_asis_anual   1041742 non-null  int64
dtypes: float64(22), int64(41), object(25)
memory usage: 699.4+ MB

None

First 5 rows of df_merged_rm:

,agno,rbd,DGV_RBD,NOM_RBD,COD_REG_RBD,nom_reg_rbd_a,COD_PRO_RBD,COD_COM_RBD,NOM_COM_RBD,COD_DEPROV_RBD,...,tasa_asistencia_5,tasa_asistencia_6,tasa_asistencia_7,tasa_asistencia_8,tasa_asistencia_9,tasa_asistencia_10,tasa_asistencia_11,tasa_asistencia_12,tasa_asistencia_anual,categoria_asis_anual
0,2019,8485,9,LICEO INSTITUTO NACIONAL,13,RM,131,13101,SANTIAGO,131,...,"0,380952380952381",1,1,"0,857142857142857","0,833333333333333","0,470588235294118",NaN,NaN,"0,755725190839695",2
1,2019,8485,9,LICEO INSTITUTO NACIONAL,13,RM,131,13101,SANTIAGO,131,...,"0,476190476190476","0,875",1,"0,80952380952381","0,833333333333333","0,470588235294118",NaN,NaN,"0,748091603053435",2
2,2019,8485,9,LICEO INSTITUTO NACIONAL,13,RM,131,13101,SANTIAGO,131,...,"0,476190476190476","0,875","0,833333333333333","0,857142857142857","0,888888888888889","0,470588235294118",NaN,NaN,"0,763358778625954",2
3,2019,8485,9,LICEO INSTITUTO NACIONAL,13,RM,131,13101,SANTIAGO,131,...,"0,380952380952381","0,625","0,5","0,857142857142857","0,833333333333333","0,411764705882353",NaN,NaN,"0,694656488549618",2
4,2019,8485,9,LICEO INSTITUTO NACIONAL,13,RM,131,13101,SANTIAGO,131,...,"0,476190476190476","0,875",1,"0,80952380952381","0,888888888888889","0,411764705882353",NaN,NaN,"0,755725190839695",2

In [7]:
# Filter df_asistencia for 'RM' region
df_asistencia_rm = df_asistencia[df_asistencia['nom_reg_rbd_a'] == 'RM'].copy()

# Filter df_rendimiento for 'RM' region
df_rendimiento_rm = df_rendimiento[df_rendimiento['NOM_REG_RBD_A'] == 'RM'].copy()

# Rename columns in df_rendimiento_rm to match df_asistencia_rm for merging
df_rendimiento_rm_renamed = df_rendimiento_rm.rename(
    columns={
        'AGNO': 'agno',
        'RBD': 'rbd',
        'MRUN': 'mrun',
        'NOM_REG_RBD_A': 'nom_reg_rbd_a' # Also rename region column for consistency
    }
)

# Perform an inner merge on 'agno' and 'mrun' for the 'RM' region data
df_merged_rm = pd.merge(
    df_rendimiento_rm_renamed,
    df_asistencia_rm,
    on=['agno', 'mrun', 'rbd', 'nom_reg_rbd_a'], # Include more common columns for robust merge
    how='inner',
    suffixes=('_rendimiento', '_asistencia')
)

print("Info of the merged DataFrame for 'RM' region:")
display(df_merged_rm.info())

print("\nFirst 5 rows of the merged DataFrame for 'RM' region:")
display(df_merged_rm.head())

Info of the merged DataFrame for 'RM' region:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1041742 entries, 0 to 1041741
Data columns (total 88 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   agno                   1041742 non-null  int64
 1   rbd                    1041742 non-null  int64
 2   DGV_RBD                1041742 non-null  int64
 3   NOM_RBD                1041742 non-null  object
 4   COD_REG_RBD            1041742 non-null  int64
 5   nom_reg_rbd_a          1041742 non-null  object
 6   COD_PRO_RBD            1041742 non-null  int64
 7   COD_COM_RBD            1041742 non-null  int64
 8   NOM_COM_RBD            1041742 non-null  object
 9   COD_DEPROV_RBD         1041742 non-null  int64
 10  NOM_DEPROV_RBD         1041742 non-null  object
 11  COD_DEPE               1041742 non-null  int64
 12  COD_DEPE2              1041742 non-null  int64
 13  RURAL_RBD              1041742 non-null  int64
 14  ESTADO_ESTAB           1041742 non-null  int64
 15  COD_ENSE               1041742 non-null  int64
 16  COD_ENSE2              1041742 non-null  int64
 17  COD_GRADO              1041742 non-null  int64
 18  LET_CUR                1041742 non-null  object
 19  COD_JOR                1041742 non-null  int64
 20  COD_TIP_CUR            1041742 non-null  int64
 21  COD_DES_CUR            1041742 non-null  int64
 22  mrun                   1041742 non-null  int64
 23  GEN_ALU                1041742 non-null  int64
 24  FEC_NAC_ALU            1041742 non-null  int64
 25  EDAD_ALU               1041742 non-null  object
 26  COD_REG_ALU            1041742 non-null  int64
 27  COD_COM_ALU            1041742 non-null  int64
 28  NOM_COM_ALU            1041742 non-null  object
 29  COD_RAMA               1041742 non-null  int64
 30  COD_SEC                1041742 non-null  int64
 31  COD_ESPE               1041742 non-null  int64
 32  PROM_GRAL              1041742 non-null  object
 33  ASISTENCIA             1041742 non-null  int64
 34  SIT_FIN                1041742 non-null  object
 35  SIT_FIN_R              1041742 non-null  object
 36  COD_MEN                1041742 non-null  int64
 37  cod_reg_rbd            1041742 non-null  int64
 38  cod_pro_rbd            1041742 non-null  int64
 39  cod_com_rbd            1041742 non-null  int64
 40  nom_com_rbd            1041742 non-null  object
 41  cod_deprov_rbd         1041742 non-null  int64
 42  nom_deprov_rbd         1041742 non-null  object
 43  rural_rbd              1041742 non-null  int64
 44  slep                   20796 non-null    float64
 45  nombre_slep            20796 non-null    object
 46  cohorte                20796 non-null    float64
 47  cod_depe2              1041742 non-null  int64
 48  cod_ense               1041742 non-null  int64
 49  cod_ense2              1041742 non-null  int64
 50  cod_grado              1041742 non-null  int64
 51  let_cur                1041742 non-null  object
 52  gen_alu                1041742 non-null  int64
 53  fec_nac_alu            1041742 non-null  int64
 54  dias_asistidos_3       1013467 non-null  float64
 55  dias_asistidos_4       1022216 non-null  float64
 56  dias_asistidos_5       1027227 non-null  float64
 57  dias_asistidos_6       942442 non-null   float64
 58  dias_asistidos_7       1033018 non-null  float64
 59  dias_asistidos_8       1036880 non-null  float64
 60  dias_asistidos_9       1038585 non-null  float64
 61  dias_asistidos_10      1038681 non-null  float64
 62  dias_asistidos_11      1006839 non-null  float64
 63  dias_asistidos_12      956359 non-null   float64
 64  dias_asistidos_anual   1041742 non-null  int64
 65  dias_trabajados_3      1013467 non-null  float64
 66  dias_trabajados_4      1022216 non-null  float64
 67  dias_trabajados_5      1027227 non-null  float64
 68  dias_trabajados_6      942442 non-null   float64
 69  dias_trabajados_7      1033018 non-null  float64
 70  dias_trabajados_8      1036880 non-null  float64
 71  dias_trabajados_9      1038585 non-null  float64
 72  dias_trabajados_10     1038681 non-null  float64
 73  dias_trabajados_11     1006839 non-null  float64
 74  dias_trabajados_12     956359 non-null   float64
 75  dias_trabajados_anual  1041742 non-null  int64
 76  tasa_asistencia_3      1013467 non-null  object
 77  tasa_asistencia_4      1022216 non-null  object
 78  tasa_asistencia_5      1027227 non-null  object
 79  tasa_asistencia_6      942442 non-null   object
 80  tasa_asistencia_7      1033018 non-null  object
 81  tasa_asistencia_8      1036880 non-null  object
 82  tasa_asistencia_9      1038585 non-null  object
 83  tasa_asistencia_10     1038681 non-null  object
 84  tasa_asistencia_11     1006839 non-null  object
 85  tasa_asistencia_12     956359 non-null   object
 86  tasa_asistencia_anual  1041742 non-null  object
 87  categoria_asis_anual   1041742 non-null  int64
dtypes: float64(22), int64(41), object(25)
memory usage: 699.4+ MB

None

First 5 rows of the merged DataFrame for 'RM' region:

,agno,rbd,DGV_RBD,NOM_RBD,COD_REG_RBD,nom_reg_rbd_a,COD_PRO_RBD,COD_COM_RBD,NOM_COM_RBD,COD_DEPROV_RBD,...,tasa_asistencia_5,tasa_asistencia_6,tasa_asistencia_7,tasa_asistencia_8,tasa_asistencia_9,tasa_asistencia_10,tasa_asistencia_11,tasa_asistencia_12,tasa_asistencia_anual,categoria_asis_anual
0,2019,8485,9,LICEO INSTITUTO NACIONAL,13,RM,131,13101,SANTIAGO,131,...,"0,380952380952381",1,1,"0,857142857142857","0,833333333333333","0,470588235294118",NaN,NaN,"0,755725190839695",2
1,2019,8485,9,LICEO INSTITUTO NACIONAL,13,RM,131,13101,SANTIAGO,131,...,"0,476190476190476","0,875",1,"0,80952380952381","0,833333333333333","0,470588235294118",NaN,NaN,"0,748091603053435",2
2,2019,8485,9,LICEO INSTITUTO NACIONAL,13,RM,131,13101,SANTIAGO,131,...,"0,476190476190476","0,875","0,833333333333333","0,857142857142857","0,888888888888889","0,470588235294118",NaN,NaN,"0,763358778625954",2
3,2019,8485,9,LICEO INSTITUTO NACIONAL,13,RM,131,13101,SANTIAGO,131,...,"0,380952380952381","0,625","0,5","0,857142857142857","0,833333333333333","0,411764705882353",NaN,NaN,"0,694656488549618",2
4,2019,8485,9,LICEO INSTITUTO NACIONAL,13,RM,131,13101,SANTIAGO,131,...,"0,476190476190476","0,875",1,"0,80952380952381","0,888888888888889","0,411764705882353",NaN,NaN,"0,755725190839695",2

### Explanation of the Steps:

1.  **Filtering by Region**: We created `df_asistencia_rm` and `df_rendimiento_rm` by filtering each original DataFrame to include only rows where the region (`nom_reg_rbd_a` in attendance, `NOM_REG_RBD_A` in rendimiento) is 'RM'. We use `.copy()` to ensure these are independent DataFrames and avoid SettingWithCopyWarning.

2.  **Renaming Columns**: Similar to our previous attempt, we renamed key columns in `df_rendimiento_rm` (`AGNO`, `RBD`, `MRUN`, `NOM_REG_RBD_A`) to `agno`, `rbd`, `mrun`, and `nom_reg_rbd_a` to facilitate a cleaner merge with `df_asistencia_rm`.

3.  **Inner Merge**: We then performed an inner merge, `df_merged_rm`, using `agno`, `mrun`, `rbd`, and `nom_reg_rbd_a` as the common keys. Using multiple identifying columns like `rbd` (school identifier) in addition to `agno` and `mrun` can make the merge more precise, ensuring we're matching records for the same student, in the same school, in the same year, and in the same region. The `suffixes` argument helps distinguish columns that have the same name but come from different original DataFrames (e.g., `COD_DEPE2_rendimiento` vs `COD_DEPE2_asistencia`).

This new `df_merged_rm` DataFrame should be significantly smaller and easier to work with, allowing us to proceed with analysis without running into RAM issues.